### PR TITLE
Add disclaimer that using this can lead to a ban.

### PR DESCRIPTION
**Pull request by hanfclippy**

### CODE REVIEW

**Comment by acheong08** [comment]
We got official notice from a Bing developer that this doesn't actually break their terms of service.

**Comment by Harry-Jing** [comment]
But the strange thing is that my account has been banned.

Now I am back into waiting list

**Comment by acheong08** [comment]
> But the strange thing is that my account has been banned.
> 
> Now I am back into waiting list

Did you break any of their other rules? We're quite sure this isn't supposed to lead to a ban. There are official Bing Chat developers in our discord and we got confirmation from them quite a while ago

**Comment by Harry-Jing** [comment]
I think it may be just a bug. 

I saw people who had never used this and encountered the same problem.

And sadly, I don't know any solution to this problem.

**Comment by Harry-Jing** [comment]
image

**Comment by BlueSchnabeltier** [comment]
> But the strange thing is that my account has been banned.
> 
> Now I am back into waiting list

Me too

**Comment by hdcola** [comment]
https://t.me/usemygptbot 如果是中文用户，可以到这个群来讨论下被ban的原因。我前两天发布了一个版本应该规避了这个问题。但是不确定，需要更多人确认一下

**Pull request closed without merging**
