### PR TITLE
Use pyproject.toml to build

### PR DESCRIPTION
**Pull request by Harry-Jing**
According to [PEP 621](https://peps.python.org/pep-0621/) and [setuptools](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html)

use pyproject.toml is more offical way to define the metadata of a project

### CODE REVIEW

**Review by acheong08 — APPROVED** [review]

**Comment by Harry-Jing** [comment]
The github workflows not need to change

**Comment by acheong08** [comment]
doesn't work from PyPi

**Comment by Harry-Jing** [comment]
How?

**Comment by acheong08** [comment]
`ModuleNotFoundError: No module named 'EdgeGPT'`

**Comment by Harry-Jing** [comment]
Del the py-module and try

**Comment by Harry-Jing** [comment]
I know where the problem is

**Comment by Harry-Jing** [comment]
It cant find EdgeGPT folder but only src folder

**Comment by acheong08** [comment]
That is how it works with setup.py

**Comment by Harry-Jing** [comment]
I didn't notice it in the src folder.

**Pull request merged**
