### PR TITLE
Better implement for using Enum 

### PR DESCRIPTION
**Pull request by Harry-Jing**
Also format code by using black

Already tested on my computer

### CODE REVIEW

**Comment by Harry-Jing** [comment]
I explained why at #100

**Comment by Arborym** [comment]
Since this is a reformatting PR using Black, it makes sense to reorder imports using isort according to PEP8 standards:
```py
import argparse
import asyncio
import json
import os
import random
import sys
import uuid
from enum import Enum
from typing import Generator, Literal, Optional, Union

import requests
import websockets.client as websockets
```
Feel free to add to your PR if you agree

**Comment by Harry-Jing** [comment]
I did not find the relevant criteria in [pep8](https://peps.python.org/pep-0008/#imports), The elements related to the import order are the following.

---
- Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants.
  Imports should be grouped in the following order:
  1. Standard library imports.
  2. Related third party imports.
  3. Local application/library specific imports.

  You should put a blank line between each group of imports
---

Sorting by word length first, then alphabetically is my personal habit.

**Comment by BeautyyuYanli** [comment]
> https://github.com/acheong08/EdgeGPT/pull/100#issuecomment-1454766166

No need to support str as the argument. It's just for cli command input, not sdk functions.

**Comment by acheong08** [comment]
I'll merge this and then format with pre-commit

**Review by acheong08 — APPROVED** [review]

**Comment by acheong08** [comment]
working well.

**Pull request merged**
