### PR TITLE
simplify cookiy handling and improve error messages if path was given…

### PR DESCRIPTION
**Pull request by Mic92**
… but cannot be opened

Before when a user supplied the --cookie-file argument it would return an incorrect error message if the file does not exist. Now it will print the exception that happens when opening the file.

In my case the /tmp/cookies.json was deleted by the system.

### CODE REVIEW

**Review by acheong08 — APPROVED** [review]

**Comment by Mic92** [comment]
Is the API even public? Just now it only is presented as a cli not a library.

**Comment by acheong08** [comment]
https://github.com/acheong08/EdgeGPT/releases/tag/0.1.24.1

oops sorry about that

> Is the API even considered public? Just now it only is presented as a cli not a library.

Yes. The intent of this is to be a library. I just haven't put in enough effort on documenting it. Now that ChatGPT is having severe issues, I'll put more time into this

**Comment by acheong08** [comment]
Currently there seems to be some bugs where the first message doesn't go through correctly. I will fix it tomorrow

**Comment by acheong08** [comment]
fixed in https://github.com/acheong08/EdgeGPT/releases/tag/0.1.25

**Comment by Mic92** [comment]
Looks like the cookies variable never gets assigned when a path is specified.
I fixed that: https://github.com/acheong08/EdgeGPT/pull/316

**Pull request merged**
